[build]
command = "npm run build"
environment = { NODE_VERSION = "18"}
functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/talkTitles.json"]

[context.production.environment]
  NODE_VERSION = "18"